//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SklyarovaDA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int id { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int role { get; set; }
        public Nullable<int> Faild_login { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<bool> is_First { get; set; }
        public Nullable<System.DateTime> Last_login { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
